version: '3.9'

services:
  ## ────────────────────────────────────
  ## ZooKeeper
  ## ────────────────────────────────────
  zookeeper:
    image: bitnamilegacy/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,TAILSCALE://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092,TAILSCALE://shahboz-shodiev.tail70e378.ts.net:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,TAILSCALE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_MESSAGE_MAX_BYTES:       5000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 5000000
      KAFKA_FETCH_MAX_BYTES:         5000000
    ports:
      - "9092:9092"
      - "29092:29092"
      - "39092:39092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/9092 && echo ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## ────────────────────────────────────
  ## Redis
  ## ────────────────────────────────────
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ## ────────────────────────────────────
  ## Worker (Python)
  ## ────────────────────────────────────
  # worker:
  #   build:
  #     context: ./worker
  #     dockerfile: worker.dockerfile
  #   # container_name: worker
  #   env_file:
  #     - .env
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  ## ────────────────────────────────────
  ## Aggregator (Go)
  ## ────────────────────────────────────
  aggregator:
    build:
      context: .
      dockerfile: aggregator/aggregator.dockerfile
    container_name: aggregator
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ingestor:
    build:
      context: ./ingestor
      dockerfile: ingestor.dockerfile
    container_name: ingestor
    env_file:
      - .env
    volumes:
    - ./dev/videos:/videos
    depends_on:
      kafka:
        condition: service_healthy

  upload-ingestor:
    build:
      context: ./ingestor
      dockerfile: ingestor.dockerfile
    container_name: upload-ingestor
    entrypoint: ["python", "-u", "upload_consumer.py"]
    env_file:
      - .env
    volumes:
      - uploads-data:/uploads
    depends_on:
      kafka:
        condition: service_healthy


  dashboard:
    build:
      context: .
      dockerfile: dashboard/dashboard.dockerfile
    container_name: dashboard
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"

  notifier:
    build:
      context: .
      dockerfile: notifier/notifier.dockerfile
    container_name: notifier
    env_file:
      - .env
    depends_on:
      redis:
          condition: service_healthy
      mailhog:
          condition: service_started  

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: postgres
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  uploads-data:
  
networks:
  default:
    driver: bridge
