# [agent]
#   interval = "1s"
#   metric_batch_size = 1000
#   metric_buffer_limit = 10000
#   log_level = "info"  # Set to "debug" for troubleshooting

# [[inputs.kafka_consumer]]
#   brokers = ["kafka:9092"]
#   topics = ["video.enriched"]
#   consumer_group = "telegraf"
#   offset = "oldest"
#   data_format = "json"
#   json_time_key = "timestamp"
#   json_time_format = "unix_ms"
#   name_override = "frame_enriched"
#   tag_keys = ["camera"]
#   tagexclude = ["host"]
#   consumer_fetch_default = 1048576

# [[outputs.influxdb_v2]]
#   urls = ["http://influxdb:8086"]
#   token = "mysecrettoken123"  # Use environment variable for security
#   organization = "example_org"
#   bucket = "video_metrics"


[agent]
  interval = "1s"
  log_level = "info"

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics  = ["video.enriched"]
  consumer_group = "telegraf"
  offset = "oldest"
  data_format = "json"
  json_time_format = "unix_ms"
  name_override = "frame_enriched"
  tag_keys = ["camera"]
  tagexclude = ["host"]

[[outputs.influxdb_v2]]
  urls   = ["http://influxdb:8086"]
  token  = "mysecrettoken123"
  organization = "example_org"
  bucket = "video_metrics"


