/** Signed URLs expire after ~300s on the backend; refresh slightly earlier. */
const CACHE_TTL_MS = 4 * 60 * 1000

const urlCache = new Map<string, { url: string; expiresAt: number }>()

/** Frame keys are UUIDs generated by the aggregator — not numeric DB ids. */
const ALERT_FRAME_ID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export function isAlertFrameId(value: string | null | undefined): value is string {
  return !!value && ALERT_FRAME_ID_RE.test(value.trim())
}

/**
 * Resolves a signed Supabase URL for an alert capture frame.
 * Falls back to null when `alertId` is missing or the image is unavailable.
 */
export function useAlertFrameImage(alertId: MaybeRefOrGetter<string | null | undefined>) {
  const api = useApi()
  const frameUrl = ref<string | null>(null)
  const loading = ref(false)
  const unavailable = ref(false)

  async function load(id: string) {
    const cached = urlCache.get(id)
    if (cached && cached.expiresAt > Date.now()) {
      frameUrl.value = cached.url
      unavailable.value = false
      return
    }

    loading.value = true
    unavailable.value = false
    try {
      const { signed_url } = await api.getAlertImage(id)
      urlCache.set(id, { url: signed_url, expiresAt: Date.now() + CACHE_TTL_MS })
      frameUrl.value = signed_url
    }
    catch {
      frameUrl.value = null
      unavailable.value = true
    }
    finally {
      loading.value = false
    }
  }

  watch(
    () => toValue(alertId),
    (raw) => {
      frameUrl.value = null
      unavailable.value = false
      if (!import.meta.client) return
      const id = raw?.trim()
      if (!isAlertFrameId(id)) return
      void load(id)
    },
    { immediate: true },
  )

  return { frameUrl, loading, unavailable }
}
